name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    env:
        CI: true
        EMAIL: ${{secrets.EMAIL}}
        PASSWORD: ${{secrets.PASSWORD}}
        SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
        SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
        WEBHOOK: ${{ secrets.WEBHOOK }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]      
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Slack notification
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: '{"text": "Test Automation Build Started"}' # Optional     
      env:
        SLACK_WEBHOOK: ${{ secrets.WEBHOOK }}  
    - run: npm ci
    - run: npm run backend
   # - run: npm install
   # - run : npm run frontend-headless
    - name: Slack notification
      id: slackFinish
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: '{"Test Automation Build Completed"}' # Optional  
      env:
        SLACK_WEBHOOK: ${{ secrets.WEBHOOK }}
