# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run backend
    - run: npm install
    - run : npm run frontend-headless
    env:
        CI: true
        EMAIL: ${{secrets.EMAIL}}
        PASSWORD: ${{secrets.PASSWORD}}
        WRONG_USER_EMAIL: 12345@gmail.com
        WRONG_PASSWORD: '12345'
        TASK_NAME: task-
        SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
        SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
    - name: Slack Notify
      uses: rtCamp/action-slack-notify@v2.0.1
    env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
   